### ISSUE TITLE
Change password is logging out

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/members#266]
Changing a password with the option set to automatically log back in, is not logging back in. :(

**Comment by TheJester12** [comment]
Yes, this is a huge bummer. Is there any manual solution I could take to fixing this?

**Comment by TheJester12** [comment]
So I don't know if this is helpful to you, (probably not), but I was able to hack my way through this and create a custom event that saves member data including passwords and doesn't log the user out. Someday hopefully this isn't necessary.

	//Added this at the top below the class.event.php import
	require_once(CORE . '/class.session.php');
	
	//Blah blah, the rest of the event code
	
	public function load(){
		if(isset($_POST['action']['member-edit'])) {
			
			//Get the Member ID from param pool
			$the_member_id = $this->_env['param']['member-id'];
			
			//Fetch the Members full entry
			$member = EntryManager::fetch($the_member_id, 1);
	
			if(!isset($_POST['fields']['email'])) {
				$memberemail = $member[0]->getData(1); // 1 is the ID of the field
				$_POST['fields']['email'] = $memberemail['value'];
			}
	
			return $this->__trigger();
		}
	}
	
	protected function __trigger(){
		
		//This runs the event and saves the new information (including a new password) to the section
		include(TOOLKIT . '/events/event.section.php');
		
		//This only runs if a new password is present
		if(isset($_POST['fields']['password']['password'])) {
			
			//This basically logs out and logs back in the user
			$_REQUEST['member-action']['login'] = 'Login';
			$_POST['fields']['password'] = $_POST['fields']['password']['password'];
			$membersExtensionThing = Symphony::ExtensionManager()->create('members');
			$membersExtensionThing->checkFrontendPagePermissions('/frontend/');
			
			//This replaces the outdated session with the old password with the new session
			$member = EntryManager::fetch($_SESSION['sym-members']['id'], 1);
			$memberpass = $member[0]->getData(2); // 2 is the id of the field
			$_SESSION['sym-members']['password'] = $memberpass['password'];
	
		}
		
		return $result;
	}

**Comment by michael-e** [comment]
Yes, there is an issue with saving a new password using a native Symphony event (and I already understand the reasons and have a fix for it). But at the same time I think that the issue posted at the top of this thread does not exist (as described), because it says:

> Changing a password with the option set to automatically log back in, is not logging back in. :(

There is no option to automatically log back in. Only the "Members: Reset Password" event has such an option, but this event is supposed to be used for a completely different thing. We must differentiate:

1. Resetting a password using the "Members: Reset Password" event: This requires a *recovery code* and a *new password*, and it provides an option to automatically log the Member back in (**which works fine, IMHO**)
2. Saving a new password: This basically only requires a frontend form and a native event; if (and only if) you want to allow an empty password to be saved, you will also need to attach the "Members: Update Password" filter, which will at the same time attempt to log the Member back in with the new password. (**The latter is broken.**)

So in order to avoid confusion, I am going to close this issue and open a new one for the second thing.

**Comment by nitriques** [comment]
Thanks @michael-e

**Comment by michael-e** [comment]
You're welcome.
