### ISSUE TITLE
Bypassing the cachelite cache 

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/members#284]
We can't exclude our frontend cms from the cachelite cache.

@nitriques : The member extension needs to bypass the cache.

> In the extension.driver.php file of the member extension. It needs to have a new method that is called by the delegate system

https://github.com/symphonists/cachelite#bypassing-the-cache

**Comment by nitriques** [comment]
@wdebusschere I've just pushed and UNTESTED commit to branch `cachelite`. I've only linted the code with `php -l` but it should get you near a working state! Can you test please ?

**Comment by wdebusschere** [comment]
Works perfect. Even don't need to exclude url of the cms anymore, because when the member is logged in the extension is bypassed. Perfect.

On the gitterchat everybody is recommanding cacheable datasource + varnish/nginx. But thats to complex for what we need.

With cacheable datasource for most datasource we get the DOMcontentloaded in +/- 1s. With cache lite extension this is +/- 400ms..
 
What are the disadvantages of cachelite, except for sessions not working?

**Comment by nitriques** [comment]
> What are the disadvantages of cachelite, except for sessions not working?

It can take lots of space on disk. And disk is not the fastest storage either. So yeah, proper caching server is better, but it does require to have access to the server and be able to configure/monitor/update the things.

Cachelite is cool because it works everywhere, without having to setup things on the server side :) I'll release this live! Thanks!
